---
title: "Data Collation and Synthesis Protocol"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{data_protocol}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## About the package

The [`epiparameter` R package](https://github.com/epiverse-trace/epiparameter) is a library of epidemiological delay distribution data and functions that read and handle this data. The delay distributions describe the time between two events in epidemiology, for example incubation periods, serial interval and onset-to-death delay distributions. The library is compiled by a process of collecting, reviewing and extracting data from peer-reviewed literature[^1], including research articles, systematic reviews and meta-analyses. 

To prevent bias in the collection or assessment of the data, a well-defined methodology of searching and refining, just as with other systematic reviews and meta-analyses, is required. This document aims to provide transparency on the methodology used by the `epiparameter` maintainers by outlining the steps taken at each stage of the data handling. This document should also facilitate reproducibility in the searches, results and appraisal steps.

There is a large body of work on the methods to best conduct literature searches and data collection as part of systematic reviews and meta-analyses[^2], which we use as the basis for our protocol. These sources are: 

- [Cochrane Handbook](https://training.cochrane.org/handbook/current) 
- [PRISMA](https://www.prisma-statement.org/)
- [Stroup et al. (2000) Meta-analysis of observational studies in epidemiology](https://jamanetwork.com/journals/jama/fullarticle/192614)

The `epiparameter` package will act as a 'living systematic review' (*sensu* [Elliot et al. 2014](https://journals.plos.org/plosmedicine/article?id=10.1371/journal.pmed.1001603)) which will be actively updated and maintained to provide the most comprehensive and reliable source of data on epidemiological delay distributions.

## Objective of `epiparameter`

As defined by the PRISMA guidelines, having a clearly stated objective helps to refine the goal of the project. `epiparameter`'s objective is to provide a collection of delay distributions for a range of infectious diseases that is as accurate, unbiased and as comprehensive  as possible. Such distributions will enable outbreak analysts to easily access these distributions for routine analysis. For example, delay distributions are necessary for: calculating case fatality rates adjusting for delay to outcome, quantifying implications of different screening measures and quarantine periods, estimating reproduction numbers, and scenario modelling using transmission dynamic models.

## Scope of package

The `epiparameter` package will span a range of infectious diseases, and including several delay distributions for each disease. The pathogens/diseases that are currently systematically searched for and included in the package library are:

- adenovirus
- ebola
- human CoV
- influenza-like illness (ILI)
- seasonal influenza
- emerging influenza
- influenza A seasonal
- influenza B seasonal
- influenza H1N1
- influenza H7N9
- marburg
- measles
- MERS CoV
- monkeypox
- parainfluenza
- rhinovirus
- respiratory syncytial virus (RSV)
- SARS-associated coronavirus
- SARS-CoV-2

The delay distributions currently included in the literature search for each pathogen/disease, and thus the package are:

- incubation period
- serial interval
- generation time
- onset to hospital admission 
- onset to death

## Guide to identifying distributions in the literature

1. **Key word searches**: when searching the literature, the use of specific search phrases to ensure the correct literature is procured is required. We recommend using a search schema that includes searching for the pathogen or the disease, and the desired delay distribution. The search phrase can optionally include a specific variant/strain. It is not advised to constrain the search based on year of publication. Examples of searches: 
- "SARS-CoV-2 incubation period"
- "ebola serial interval"
- "influenza H7N9 onset to admission"

1. **Literature search engines**: we recommend using a selection of search engines to prevent one source potentially omitting papers. Recommended search sites are: Google Scholar, Web of Science, PubMed, and Scopus. Across each site we performed the same search.  

1. **Adding papers**: the papers collected in the literature search can be supplemented by papers known to be relevant or through being cited by a paper in the literature search. Papers may be recommended by experts in the research or public health community. We plan to use two methods of community engagement. Firstly a open-access Google sheet allows people to add their distribution data which will then be reviewed by one of the `epiparameter` maintainers and incorporated if it meets quality checks. The second method - not yet implemented - involves community members uploading their data to [zenodo](https://zenodo.org/), which can then be read and loaded into R using `epiparameter` once checked. 

1. **Language restrictions**: papers in English or Spanish are currently supported in `epiparameter`. Papers written in another language but verified by an expert can also be included in the database. However, these are not evaluated with the review process described below and as a result are flagged to the user when loaded in `epiparameter`.

## Guide to data refinement once sources identified

1. **Removing duplicates**: studies that use multiple data sources should be screened against other papers included to ensure the the same data sets are not being included multiple times in `epiparameter`. This is done by checking whether papers are the primary source of data or are retrieving and citing from another primary source.

1. **Abstract and methods screening**: once a number of unique sources have been identified, each should be reviewed for its suitability by reviewing the abstract and searching for words or phrases in the paper that indicate it inferred a delay distribution, this can include searching the methods section for words on types of distributions (e.g. lognormal), fitting procedures (e.g. maximum likelihood or bayesian), or searching the results for parameter estimates. If no distribution is described, the paper can be considered unsuitable at this stage.

    A database of unsuitable papers will be kept to remind maintainers which papers have not been included and aids in the updating of the databse (see below) by preventing redundant reviewing a previously rejected paper.

1. **Stopping criteria**: for many searches, the number of results is far larger than could be reasonably evaluated outside a full systematic review. After refining which papers contain the required information (abstract and methods screening), we recommend screening 10 papers per pathogen for each search (per search round, see updating section below for details). If the number of papers that pass the abstract and methods screening is fewer than 10 we recommending reviewing all suitable papers.

1. **Full paper screening**: after the abstract and methods screening, those papers not excluded should be reviewed in full to verify they indeed contain the required information on delay distribution parameters and information on methodology used. It is acceptable to include a secondary source that contains information on the delay distribution when the primary source is unavailable or does not report the distribution. The inference of the delay distribution does not have to be a primary subject of the research article, for example if it was later inferred to be used in estimation of $R_0$ it can still be included in the database. Additionally, distribution parameters based on illustrative values for use in simulations - rather than inferred from data - are considered unsuitable and should be excluded.

    Again, any papers excluded at this stage should be recorded in the database of unsuitable sources with reasoning to prevent having to reassess when updating the database.

1. **Post hoc removal**: if any `epiparameter` parameters are later identified as being inappropriate then they can be removed from the database. In most cases this is unlikely as limitations can be appended onto data entries to make users aware of limitations (e.g. around assumptions used to infer the distirbution), only in the most extreme cases will data be completely removed from the database.

Note: systematic reviews focusing on effect sizes can be subject to publication bias (e.g. more positive or significant results in the literature). However, delay distribution inference does not focus on significance testing or effect sizes, so this bias is not considered in the collection process.

## Guide to extracting parameters

1. **Extracting parameters**: for any underlying distributions (e.g. gamma, lognormal), parameters (e.g. shape/scale, meanlog/sdlog), and summary statistics (e.g. mean, standard deviation, median, range or quantiles) given in the paper, values should be recorded verbatim from the paper into the database. When these are read into R using the `epiparameter` package, other aspects of the distribution are automatically calculated and available. For example if the mean and standard deviation of a gamma distribution is reported for a serial interval these values will be stored in the database. But once in R, the shape and scale parameters of the gamma distribution, as well as the confidence intervals, will be automatically reconstructed and the resulting distribution available for use.

The minimal dataset that is required to be included in the `epiparameter` library is:

- Either pathogen name or disease name
- Type of delay distribution
- The name of the first author, optionally co-autors or 'et al' can be added 
- The year of publication
- The sample size of the data set used to fit the distribution
- The type of distribution fitted, either the only distribution fit or the best-fit from a set of candidate distributions
- Parameters or summary statistics for the distribution, these must be one of:
    - Parameter of the distribution (e.g. shape and scale in the case of gamma, meanlog and sdlog in the case of lognormal, etc.)
    - Mean and standard deviation (or equivalently variance or coefficient of variation)
    - Median and range
    - Any two quantiles. Ideally there would be a lower quantile (q < 0.5) and an upper quantile (q > 0.5) to ensure reliable estimation of parameters
- Whether the distribution fitted was discrete, this is a boolean (true or false).
- The Digital Object Identifier (DOI) of the paper

Data that are recommended but not essential:

- Uncertainty in the estimated parameters or summary statistics (central tendency and variance), this needs to be provided with the type of uncertainty characterisation, e.g. confindence interval, credible interval, etc., to avoid potential misuse of uncertainty
- Additional unique identifiers for a paper, for exampel PubMed ID (PMID) 
- Whether the distribution fitted adjusted for phase bias
- Whether the disribution used interval-censoring
- The region the data was collected, at either a natioanl, continental or global level
- The time period of data collection
- 'Notes': this can include general statements about the distribution or methodology used in the paper. These notes can be accessed when using the package to make users aware of possible limitations in the distribution parameters that may not fit in other categories


## Data quality assessment in `epiparameter`

The inference of parameters for a delay distribution often requires methological adjustments to correct for factors that would otherwise bias the estimates. These includes accounting for interval-censoring of the data when the timing of an event (e.g. exposure to a pathogen) is not know with certainty, but rather within a time window. Or adjusting for phase bias when the distribution is estimated during a growing or skrinking stage of an epidemic. The aim of `epiparameter` is not to make a judgement on which parameters are 'better' than others, but to notify and warn the user of the potential limitations of the data. These warnings are derived from the information listed in the Guide to extracting parameters section above.

Example warnings to the user may include:

- The point estimate of the distribution parameters or summary statistics were reported without any uncertainty
- The paper only fit a single type of distribution (e.g. gamma) which may not be the best fit distribution when contrasted to others, for example lognormal or weibull

The list of methodological criteria include (this is still a work in progress):

- Does the method include single or double interval-censoring when the exposure or onset times are not known with certainty (i.e. on a single day)
- Does the method adjust for phase bias when the outbreak is in an ascending or descending phase, or does the paper not mention whether the incidence is increasing or decreasing.
- Does the method fit more than one probaility distribution to the data to prevent model inadequacy.


## Diagnostics

To make sure the data extracted from papers are accurate and matches the distribution plots (if provided) in the paper, we have a set of diagnostic tools to enable the checking of values. It is possible that in the expedited nature of writing reports in the midst of epidemics that errors occur in the reporting of parameter values. The diagnostic tools provided by `epiparameter` allow for checking that the values are consistent and plausible.

Diagnostic checks can be carried out with the `epiparameter::run_diagonostic()` function in R. These include:

- plotting the distributions from the parameter estimates, this can be compared (visually) any plots in the paper to make sure the moments (e.g. mean, variance, skewness, kurtosis) approximately correspond
- converting between parameters and mean and standard deviation when both are provided to check they match
- calculating the confidence interval when mean and standard deviation are provided and check they match confidence intervals reported (if available)

## Guide to the `epiparameter` review process

For a set of parameters to be included in the database it must pass the abstract and methods screening and full screening and subsequently a review by one of the `epiparameter` maintainers. This process involves running the diagnostic checks and cross-referencing the reported parameters with those in the paper to ensure they match exactly and that the results plot of the PDF/CDF/PMF matches anything plotted in the paper, if available. This prevents a possible misinterpretation (e.g. serial interval for incubation period). This check also includes making sure the unique identifiers for the paper match the author's name, publication year and other data recorded in the database.

## Updating parameters in the database

Because search and review stages are time consuming and cannot be continuously carried out, we aim to keep the `epiparamter` library up-to-date as a living data library by conducting regular searches (i.e. every 3-4 months) to fill in any missing papers or new publication since the last search. The epidemiological literature can expand rapidly, especially during a new outbreak. Therefore we can optionally include new studies that are of use to the epidemiological community in between regular updates. These small additions will still be subject to the data quality assessment and diagnostics to ensure accuracy, and will likely be picked up in the subsquent literature searches. It is likely that for existing pathogens that have not had a major increase in incidence since the last update few new papers will be reporting delay distributions. In these cases papers that were not previously reviewed due to limited reviewing time for each round of updates are now checked.

We particularly value community contributions to the database, so everyone can benefit from analysis that has already been conducted, and duplicated of effort is reduced.

## Database of excluded papers

All papers that are returned in the search results but are not suitable, either at the stage of abstract screening, or after reviewing the entirety of the paper, are recorded in a database by the following information:

- First author's last name
- Unique identifier, ideally the DOI
- Journal, pre-print server, or host website
- One or several reasons for why it was deemed unsuitable
- Date of recording

[^1]: We also include distribution parameters that are published on pre-print servers such as arxiv or biorxiv. But will update the citation reference once the paper is accepted and published by a journal. 

[^2]: `epiparameter` is itself not a meta-analytic tool, but the references stored within may be useful as part of a meta-analysis.